### ISSUE TITLE
Reregistration discards previous readiness ?

### ISSUE THREAD

**Issue by blabaere** [alexcrichton/mio-named-pipes#1]
Hello,

While integrating mio-named-pipes in [scaproust](https://github.com/blabaere/scaproust) I ran into the following problem. Each '_connection_' goes through a handshake phase before being used to exchange messages. There is a registration or re-registration at the start of each step. When everything works fine, it goes like this:
- register writable level
- polled writable, sends handshake to peer
- register readable level
- polled readable, reads handshake sent by peer
- register all, edge
- usually polled writable
- We are now ready to exchange messages !

But with the client named pipe, it seems that the 'read' readiness is lost when re-registering for readable. The server does not have this problem. I added a test to reproduce the problem and activated the mio logs.

[Source code of the test](https://github.com/blabaere/mio-win-inv/blob/master/src/named_pipe.rs#L114)
[Appveyor build with logs](https://ci.appveyor.com/project/blabaere/mio-win-inv/build/1.0.29/job/bh6369cciy75icsq#L138)

It seems that mio sees the client pipe as readable|writable while user code registered only 'writable', and after re-registration for only 'readable', that information is lost somewhere.

This handshake workflow is currently working with both TCP (Windows and Linux) and Unix domain socket. I could create some specialized code for named pipes but I would like to know if my scenario could be supported by mio-named-pipes before going that way.

**Comment by alexcrichton** [comment]
Oh dear after reading the code a bit I discovered an [embarassing typo bug](https://github.com/alexcrichton/mio-named-pipes/commit/a29c38f2f012b6a811248169605d35d34ea55afd). Could you try testing against that commit and see if it fixes the issue for you?

This should definitely work regardless!

**Comment by blabaere** [comment]
The test written for this bug is [now passing](https://ci.appveyor.com/project/blabaere/mio-win-inv/build/1.0.33/job/723fqi36fu70u12q). And 2 out of 3 scaproust tests using mio-named-pipes are also passing. I think we can consider this fixed. 

Thanks a lot for the fast reaction !

**Comment by alexcrichton** [comment]
Awesome, glad to hear! I'll make a release with that fix now.
