### ISSUE TITLE
The crate can't work

### ISSUE THREAD

**Issue by ChijinZ** [alexcrichton/mio-named-pipes#4]
I found that your crate can't run successfully. The test code as follow: 
````
extern crate mio_named_pipes;
fn main() {
     mio_named_pipes::NamedPipe;
}
````
And error information as follow: 
````
error[E0425]: cannot find value `NamedPipe` in module `mio_named_pipes`
 --> src/main.rs:5:23
  |
5 |      mio_named_pipes::NamedPipe;
  |                       ^^^^^^^^^ not found in `mio_named_pipes`
````

And your testcases also can't work. Hopping for fixing.

**Comment by alexcrichton** [comment]
This crate only works on Windows, on other platforms it's a noop. Are you compiling on Windows?

**Comment by ChijinZ** [comment]
Oh, I forgot it only for windows. Sorry about that.
