### ISSUE TITLE
Question: The poll() on server side does not return after a client connects to the pipe

### ISSUE THREAD

**Issue by foresthan** [alexcrichton/mio-named-pipes#6]
I am trying to integrate this crate to my project to make inter-processes communication. In the following simple prototype codes (modified from the test codes in this crate), I create two executables (two exe files). Server starts first, then the client connects to the pipe. After the client sends several bytes to the pipe successfully, on the server side, poll.poll() does not return. Did I register the Evented pipe to the Poll incorrectly? Thanks a lot.

----- The client simply sends several bytes -----

    fn main() {
        let poll = check!(Poll::new());
        let mut events = Events::with_capacity(128);
        let mut opts = OpenOptions::new();
        opts.read(true)
            .write(true)
            .custom_flags(FILE_FLAG_OVERLAPPED);
        let file = t!(opts.open(r"\\.\pipe\my-pipe"));
        let mut client_pipe: NamedPipe = NamedPipe::from_raw_handle(file.into_raw_handle());
        t!(poll.register(&client_pipe, Token(1), Ready::writable() | Ready::readable(), PollOpt::edge()));  
    
        t!(poll.poll(&mut events, None));  
        for event in events.iter() {
            match event.token() {
                Token(1) => {
                    if event.readiness().is_writable() {
                        t!(client_pipe.write(b"1234"));
                        t!(client_pipe.flush());
                        debug!("Data are sent successfully");
                    }
                },
                _ => {
                    panic!("unknown token");
                }
            }
        }
    }

----- The server simply receives -----

    fn main() {
        let mut events = Events::with_capacity(128);
        let mut server_pipe: NamedPipe = t!(NamedPipe::new(r"\\.\pipe\my-pipe"));
        let poll = t!(Poll::new());
        t!(poll.register(&server_pipe, Token(0), Ready::writable() | Ready::readable(), PollOpt::edge()));  

        loop {
            t!(poll.poll(&mut events, None));    // ===> The poll() never return here
            for event in events.iter() {
                 // Try to read data from pipe.  The code does not go to here, why?
                ... ... 
            }
        }
    }

**Comment by bbqsrc** [comment]
Closing this old issue. If there's still a problem, feel free to open another.
